### PR TITLE
Convert to Gradle (Android Studio) project

### PR DESCRIPTION
**Pull request by capi**
Since Google has deprecated Android Tools for Eclipse, I propose converting this to an Android Studio / Gradle project. This PR makes this a pure gradle-based project, that compiles pretty well from CLI and from inside Android Studio.

### CODE REVIEW

**Comment by N0ury** [comment]
Hi capi,

Goog idea, merge is done.

Regards

Noury

**Comment by capi** [comment]
@nbenm My conversion no longer includes the `bin` folder, since I don't think the APKs should be part of the git repo. If you still want to provide built binaries, I'd recommend creating a tag and attaching the binary to the tag here on Github.

**Comment by N0ury** [comment]
Ok, thanks capi. Some people don't like getting the app from Google Play.
In fact I'm very new to Android Studio, and its CLI. I need some training.
I'm also going to put the app on f-droid as asked in issue #14

**Comment by capi** [comment]
If you push a git-tag to github, you can attach files (like the APK) to it for direct download. I think this is better than checking it in.

I don't know if you are working from Windows or Linux, but if you are using a shell, you can build the whole application using `./gradlew assemble` and you'll find the APK files in the `build` directory. What's currently not configured is the key-store you will need to use to sign for uploading to Play Store.

**Pull request merged**
