### PR TITLE
Fix keyboard auto correction

### LINKED ISSUE #8: [Bug] "Password mode" for keyboard enabled when editing notes
Hello,

I'm using TouchPal keyboard, so i don't know if this is a general bug or specific to using ImapNote2 with TouchPal:
When creating or editing notes within the app the TouchPal keyboard is in "password mode". This means swiping, auto spell correction and word suggestions are disabled. I don't think this is necessary for notes.
Maybe this could be changed so that notes can be created and editing with full keyboard functionality?

Thanks in advance!

### PR DESCRIPTION
**Pull request by capi**
This PR fixes the following issues:
- server name in account settings is no longer auto-corrected
- new and existing notes now have auto-correction from the keyboard (fixes #8)

### CODE REVIEW

**Comment by N0ury** [comment]
Hi capi,
This fix has been added
Thanks a lot

Regards

Noury

**Comment by capi** [comment]
@nbenm You closed without merging it?

**Comment by capi** [comment]
Ah, you applied the patch directly, without merging the PR, all clear :)

**Comment by N0ury** [comment]
Hi Martin,

I don't know why git gave me errors, so I've added your fix manually.

**Comment by capi** [comment]
Most likely because I had the PR against the Eclipse version and not the Android Studio project layout.

**Pull request closed without merging**
